name: Go Cross-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            ext: .exe
          - os: darwin # macOS
            arch: amd64
            ext: ''
          - os: linux
            arch: amd64
            ext: ''

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -v -o build/promptbuilder${{ matrix.ext }} ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: promptbuilder-${{ matrix.os }}-${{ matrix.arch }}
        path: build/myapp${{ matrix.ext }}
